version: '3.2'

networks:
  default-1:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.203.0.0/16
         gateway: 172.203.0.1
volumes:
  modulos_tryton:
    external: true

services:
  tryton:
    build:
      context: ./Tryton/.
      network: host
    volumes:
      - 'modulos_tryton:/home/gnuhealth/gnuhealth/tryton/server/trytond-6.0.24/trytond/modules'
    depends_on:
    - db
    ports:
      - "${TRYTON_PORT}:8000"
    networks:
      default-1:
        ipv4_address: 172.203.0.3
    command: ["./trytond", "-c", "/etc/trytond.conf", "-d", "gnuhealth", "-v", "--dev"]
  db:
    build: ./PG/.
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata13:/var/lib/postgresql/data/pgdata
    networks:
      default-1:
        ipv4_address: 172.203.0.2

