version: '3.2'
services:
  tryton:
    build: 
      context: ./Tryton/
      network: host
    volumes:
      - modulos-tryton:/home/gnuhealth/gnuhealth/tryton/server/trytond-6.0.24/trytond/modules
    depends_on:
    - db
    ports:
      - "8008:8000"
    networks:
      default-1:
        ipv4_address: 172.203.0.3
    command: ["./trytond", "-c", "/etc/trytond.conf", "-d", "gnuhealth", "-v", "--dev"]
  db:
    build: ./PG/
    environment:
      - POSTGRES_DB=gnuhealth
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=gnuhealth
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata13:/var/lib/postgresql/data/pgdata
    networks:
      default-1:
        ipv4_address: 172.203.0.3

networks:
  default-1:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.203.0.0/16
         gateway: 172.203.0.1

volumes:
  modulos-tryton:
    driver: local
    driver_opts:
      type: none
      device: ./modulos_tryton
      o: bind
